Repository spiffe/tornjak, pull requests merged in 2024-04, with the labels that each got.

#387 Push image on push event except dependabot
  .github/workflows/master-build.yaml
Labels: github_actions, CI Enhancement

#388 Update to Golang v1.22
  .github/actions/build/action.yaml
  .github/workflows/ci.yaml
  Dockerfile.backend-container
  Dockerfile.backend-container.ubi
  Makefile
  api/agent/server.go
  cmd/agent/main.go
  go.mod
  go.sum
  pkg/agent/auth/keycloak.go
  pkg/agent/auth/keycloak_claim.go
  pkg/agent/db/sqlite.go
  pkg/agent/db/sqlite_test.go
  pkg/agent/db/sqlite_txhelpers.go
Labels: backend

#397 Add audience claim check (#363)
  api/agent/server.go
  api/agent/types.go
  docs/conf/agent/full.conf
  docs/config-tornjak-server.md
  docs/feature_auth.md
  docs/plugin_server_auth_keycloak.md
  docs/user-management.md
  examples/keycloak/README.md
  examples/keycloak/client/tornjak-keycloak-client-import.json
  examples/keycloak/config.yaml
  examples/keycloak/realm/tornjak-realm.json
  go.mod
  go.sum
  pkg/agent/auth/keycloak.go
  pkg/agent/auth/keycloak_claim.go
  pkg/agent/auth/keycloak_test.go
Labels: IAM, backend

#398 Add issuerURL info in OIDC Discovery error handling (#394)
  pkg/agent/auth/keycloak.go
Labels: backend

#400 Update Compatibility Matrix (#396)
  USAGE.md
  docs/quickstart/server-statefulset-examples/backend-sidecar-server-statefulset.yaml
Labels: documentation

#401 Dynamic auth client_id and keycloak_realm Env Variables
  USAGE.md
  docs/user-management.md
  frontend/.env
  frontend/.env.prod
  frontend/src/auth/KeycloakAuth.js
  frontend/src/env.ts
Labels: enhancement, frontend

#403 Fixed version in documentation
  docs/user-management.md
Labels: documentation

#402 Merge v1.6 into main
  .github/actions/build/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/master-build.yaml
  Dockerfile.backend-container
  Dockerfile.backend-container.ubi
  Makefile
  USAGE.md
  api/agent/server.go
  api/agent/types.go
  cmd/agent/main.go
  docs/conf/agent/full.conf
  docs/config-tornjak-server.md
  docs/feature_auth.md
  docs/plugin_server_auth_keycloak.md
  docs/quickstart/server-statefulset-examples/backend-sidecar-server-statefulset.yaml
  docs/user-management.md
  examples/keycloak/README.md
  examples/keycloak/client/tornjak-keycloak-client-import.json
  examples/keycloak/config.yaml
  examples/keycloak/realm/tornjak-realm.json
  frontend/.env
  frontend/.env.prod
  frontend/Dockerfile.frontend-container.ubi
  frontend/package-lock.json
  frontend/src/auth/KeycloakAuth.js
  frontend/src/env.ts
  go.mod
  go.sum
  pkg/agent/auth/keycloak.go
  pkg/agent/auth/keycloak_claim.go
  pkg/agent/auth/keycloak_test.go
  pkg/agent/db/sqlite.go
  pkg/agent/db/sqlite_test.go
  pkg/agent/db/sqlite_txhelpers.go
  version.txt
Labels: Ready For Review

#408 Automate version compute for CI
  .github/compute-version/action.yaml
  .github/workflows/master-build.yaml
Labels: CI Enhancement
